# 模拟交易最近总是报错

2015-08-16 12:15 [SYS FATAL] 策略初始化失败: initialize() internal error line 16, in initialize File "python2.7/site-packages/pybrain/tools/customxml/networkreader.py", line 32, in readFrom r = NetworkReader(filename, newfile = False) File "python2.7/site-packages/pybrain/tools/customxml/handling.py", line 20, in init self.dom = parse(filename) File "python2.7/xml/dom/minidom.py", line 1918, in parse return expatbuilder.parse(file) File "python2.7/xml/dom/expatbuilder.py", line 922, in parse fp = open(file, 'rb') IOError: [Errno 2] No such file or directory: 'net.csv'

×××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××

2015-08-16 12:14 [SYS FATAL] 策略初始化失败: define global error line 14, in code NameError: name 'pd' is not defined

×××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××

2015-06-29 10:35 [SYS INFO] 策略初始化成功
2015-08-03 06:30 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 27, in handle_data IndexError: list index out of range
2015-08-10 06:15 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 27, in handle_data IndexError: list index out of range