# 策略回测quartz的benchmark数据缺失

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<mercury-input-4-617012e6f391> in <module>()
    176         perf = quartz.perf_parse(bt, quartz_acct)
    177     else:
--> 178         idxmap_all, data_all = quartz.sim_condition.data_generator.get_daily_data(sim_params)
    179 
    180         QUARTZ_CACHE['start'] = sim_params.first_trading_day

python2.7/site-packages/quartz/sim_condition/data_generator.pyc in get_daily_data(sim_params, fq)
     26     trading_days = sim_params.trading_days
     27     idxmap_date = dict(zip(trading_days, range(len(trading_days))))
---> 28     idxmap_bm, data_bm = load_benchmark_data(sim_params.benchmark, trading_days)
     29 
     30     stocks, funds = univ_divide(sim_params.universe)

python2.7/site-packages/quartz/data/benchmarks.pyc in load_benchmark_data(symbol, trading_days)
    141     # 数据缺失
    142     if len(data) != len(trading_days):
--> 143         raise ValueError("Data Incomplete!")
    144 
    145     cols = cols[2:] + ['return']  # 更正列名

ValueError: Data Incomplete!