# 貌似csv数据源出错导致MktIndustryFlowOrderGet返回报错

代码：

DataAPI.MktIndustryFlowOrderGet(beginDate=u"20160610",endDate=u"20160613",field=u"",pandas="1")

返回：

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
&lt;mercury-input-10-555c94b11d45&gt; in &lt;module&gt;()
----&gt; 1 DataAPI.MktIndustryFlowOrderGet(beginDate=u"20160610",endDate=u"20160613",field=u"",pandas="1")

python2.7/site-packages/DataAPI/DATAYES.pyc in MktIndustryFlowOrderGet(tradeDate, beginDate, endDate, field, pandas)
   7028 
   7029         if csvString is None or len(csvString) == 0 or (csvString[0] == '-' and csvString[1] != '1') or csvString[0] == '{':
-&gt; 7030             raise Exception(('%s for request: %s' % (csvString if csvString is not None else 'Query Error', 'Please try again, or check the input parameters')))
   7031         elif csvString[:2] == '-1':
   7032             csvString = ''

Exception: -2:Illegal Request Parameter for request: Please try again, or check the input parameters

这是数据源的问题吗？