# [bug]set_universe不可用报错

昨晚还是正常的，今天早上调研，set_universe('HS300')
会导致universe错误。不确定是否是bug