# Bug反馈，怀疑变量universe在运行时发生变化


使用account.universe[x] 来访问股票池时，回测过程中，universe发生未知变化，突然报错IndexError: list index out of range