# 请教大神，UnboundLocalError错误

UnboundLocalError                         Traceback (most recent call last)
&lt;mercury-input-1-64C6E17068E745A6A106EE3C6433566A&gt; in &lt;module&gt;()
    141                                             security_cost=security_cost, max_history_window=max_history_window,
    142                                             accounts=accounts, preload_data=_QUARTZ_PRELOAD_DATA,
--&gt; 143                                             display=True, return_quartz_data=True)
    144     _QUARTZ_CACHE['start'] = start
    145     _QUARTZ_CACHE['end'] = end

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/backtest.pyc in backtest(start, end, benchmark, universe, capital_base, initialize, handle_data, post_trading_day, commission, slippage, refresh_rate, freq, security_base, security_cost, max_history_window, accounts, *args, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/backtest.pyc in backtest_daily(context, backtest_calendar, backtest_data_roller, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/context/context.pyc in handle_data(self)

&lt;mercury-input-1-64C6E17068E745A6A106EE3C6433566A&gt; in handle_data(account)
     94 
     95     for str in account.universe:
---&gt; 96         MA5 = hist1[str].mean()                                       #计算过去5个交易日及过去30个交易日的均价
     97         MA30 = hist2[str].mean()
     98         if str in account.avail_security_position:

UnboundLocalError: local variable 'hist1' referenced before assignment