# 优矿回测是不是有好多bug！

KeyError                                  Traceback (most recent call last)
&lt;mercury-input-4-73C7C40D02B649C39EBE972B2C7DC7A9&gt; in &lt;module&gt;()
    153                                             security_cost=security_cost, max_history_window=max_history_window,
    154                                             accounts=accounts, preload_data=_QUARTZ_PRELOAD_DATA,
--&gt; 155                                             display=True, return_quartz_data=True)
    156     _QUARTZ_CACHE['start'] = start
    157     _QUARTZ_CACHE['end'] = end

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/backtest.pyc in backtest(start, end, benchmark, universe, capital_base, initialize, handle_data, post_trading_day, commission, slippage, refresh_rate, freq, security_base, security_cost, max_history_window, accounts, *args, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/backtest.pyc in backtest_daily(context, backtest_calendar, backtest_data_roller, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/context/context.pyc in handle_data(self)

&lt;mercury-input-4-73C7C40D02B649C39EBE972B2C7DC7A9&gt; in handle_data(context)
     34     for stock in havingbuylist:
     35         if stock  in current_universe:
---&gt; 36             if account.reference_price[stock]/account.security_cost[stock]-1&lt;-0.05:
     37                 print stock
     38                 havingbuylist.remove(stock)

KeyError: '601222.XSHG'
这个我感觉应该是没有这个股票的数据，我是做止损的，没有这个股票的数据怎么弄啊