# account.order出现ValueError异常

**策略如下：**
from datetime import datetime

start = '2015-04-09'                       # 回测起始时间
end = '2015-04-11'                         # 回测结束时间

benchmark = '000300.ZICN'                        # 策略参考标准
universe = ['161010.XSHE', '511010.XSHG']  # 证券池，支持股票和基金
capital_base = 1000000                      # 起始资金
freq = 'd'                                 # 策略类型，'d'表示日间策略使用日线回测，'m'表示日内策略使用分钟线回测
refresh_rate = 1                           # 调仓频率，表示执行handle_data的时间间隔，若freq = 'd'时间间隔的单位为交易日，若freq = 'm'时间间隔为分钟
    
def initialize(account):                   # 初始化虚拟账户状态
    pass

def handle_data(account):                  # 每个交易日的买入卖出指令
    log.info (account.current_date)
    account.order ('161010.XSHE', 100)
    
**错误如下：**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
&lt;mercury-input-5-B8D240CA83694AD1BC581A6064D79FAA&gt; in &lt;module&gt;()
     56                                             accounts=accounts, preload_data=_QUARTZ_PRELOAD_DATA,
     57                                             display=True, return_quartz_data=True,
---&gt; 58                                             threaded=quartz_createVar.get('threaded', True))
     59     _QUARTZ_CACHE['start'] = start
     60     _QUARTZ_CACHE['end'] = end

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/backtest.pyc in backtest(start, end, benchmark, universe, capital_base, initialize, handle_data, post_trading_day, commission, slippage, refresh_rate, freq, security_base, security_cost, max_history_window, accounts, threaded, display, preload_data, *args, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/backtest.pyc in bt_algorithm(clock, trading_scheduler, trading_agent, threaded)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/trading_agent.pyc in settlement(self)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/pms/pms_lite.pyc in post_trading_day(self, feedback_info, dividend, split)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/pms/pms_lite.pyc in _record_dividend(self, account, config)

/home/ipython/anaconda/lib/python2.7/site-packages/pandas/tslib.so in pandas.tslib._make_error_func.f (pandas/tslib.c:15412)()

ValueError: NaTType does not support strftime

这是为何？