# pandas 读取文件失败

我把closeprice.csv（来自《Python与量化投资》一书）文件放在桌面，然后运行代码（代码在第70页）

import pandas as pd
data=pd.read_csv('C:/Users\lenovo\Desktop\closeprice.csv',encoding='gbk',dtype={'ticker'})
data

然后提示非常长的错误信息，如下：
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-2cd24ffb2129> in <module>()
      1 import pandas as pd
----> 2 data=pd.read_csv('C:/Users\lenovo\Desktop\closeprice.csv',encoding='gbk',dtype={'ticker'})
      3 data
      4 

D:\Program Files\anaconda\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    676                     skip_blank_lines=skip_blank_lines)
    677 
--> 678         return _read(filepath_or_buffer, kwds)
    679 
    680     parser_f.__name__ = name

D:\Program Files\anaconda\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    438 
    439     # Create the parser.
--> 440     parser = TextFileReader(filepath_or_buffer, **kwds)
    441 
    442     if chunksize or iterator:

D:\Program Files\anaconda\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    785             self.options['has_index_names'] = kwds['has_index_names']
    786 
--> 787         self._make_engine(self.engine)
    788 
    789     def close(self):

D:\Program Files\anaconda\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1012     def _make_engine(self, engine='c'):
   1013         if engine == 'c':
-> 1014             self._engine = CParserWrapper(self.f, **self.options)
   1015         else:
   1016             if engine == 'python':

D:\Program Files\anaconda\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1706         kwds['usecols'] = self.usecols
   1707 
-> 1708         self._reader = parsers.TextReader(src, **kwds)
   1709 
   1710         passed_names = self.names is None

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

D:\Program Files\anaconda\lib\site-packages\pandas\core\dtypes\common.py in pandas_dtype(dtype)
   2011 
   2012     try:
-> 2013         npdtype = np.dtype(dtype)
   2014     except (TypeError, ValueError):
   2015         raise

TypeError: data type not understood

请问，这个问题怎么解决。