# 在cmd里面输入“pip install mysql client”,无法成功；

1，在cmd里面输入“pip install mysql client”
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
Command ""c:\program files (x86)\python36-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\morgan-1\\AppData\\Local\\Temp\\pip-build-9rvouple\\mysqlclient\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\morgan-1\AppData\Local\Temp\pip-maz_wrv8-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\morgan-1\AppData\Local\Temp\pip-build-9rvouple\mysqlclient\
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
    ----------------------------------------
2，然后我输入python -m pip install --upgrade pip，
反馈如下：
Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
PermissionError: [WinError 5] 拒绝访问。: 'c:\\program files (x86)\\python36-32\\lib\\site-packages\\pip-9.0.3.dist-info\\description.rst' -> 'C:\\Users\\morgan-1\\AppData\\Local\\Temp\\pip-pp693ohy-uninstall\\program files (x86)\\python36-32\\lib\\site-packages\\pip-9.0.3.dist-info\\description.rst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pip\req\req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pip\req\req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pip\req\req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pip\utils\__init__.py", line 267, in renames
    shutil.move(old, new)
  File "C:\Program Files (x86)\Python36-32\lib\shutil.py", line 559, in move
    os.unlink(src)
PermissionError: [WinError 5] 拒绝访问。: 'c:\\program files (x86)\\python36-32\\lib\\site-packages\\pip-9.0.3.dist-info\\description.rst'
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

请问该怎么解决？谢谢各位大神；