# 场外基金策略KeyError

```python
start = '2018-01-01'                       # 回测起始时间
end = '2018-11-01'                         # 回测结束时间
benchmark = 'HS300'                        # 策略参考标准
freq = 'd'                                 # 策略类型，'d'表示日间策略使用日线回测，'m'表示日内策略使用分钟线回测
refresh_rate = 1                           # 调仓频率，表示执行handle_data的时间间隔，若freq = 'd'时间间隔的单位为交易日，若freq = 'm'时间间隔为分钟
accounts = {
        'otc_fund': AccountConfig('otc_fund', capital_base=10000, 
                                      commission=Commission(buycost=0.001, sellcost=0.001, unit='perValue')
}
fund_sec = DataAPI.SecIDGet(assetClass=u"F",pandas="1")
universe = fund_sec['secID'].values.tolist()
def initialize(context):
    pass

# 每个单位时间(如果按天回测,则每天调用一次,如果按分钟,则每分钟调用一次)调用一次
def handle_data(context):
    today = context.current_date
    gdf = pd.read_csv('self/products-2018-01-01.csv', dtype={'子产品代码':str, '子产品比例':float })
    
    account = context.get_account('otc_fund')
    if account.cash > 5000:
        print(account.cash)
        for fund, ratio in gdf[['子产品代码', '子产品比例']].values:
            print('purchase %s for %s cash' % (fund, (account.cash - 100) * ratio))
            account.purchase('%s.OFCN' % fund, (account.cash - 100) * ratio)
                
```

策略比较简单， 就是想从之前写的一个配置文件中读取，然后下单，但是回测了几天后， 提示 KeyError



```
10000.0
purchase 162414 for 330.66 cash
purchase 164509 for 2640.33 cash
purchase 511230 for 2638.35 cash
purchase 501023 for 329.67 cash
purchase 161124 for 329.67 cash
purchase 165526 for 330.66 cash
purchase 164208 for 2640.33 cash
purchase 501000 for 330.66 cash
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<mercury-input-8-A4C431D14F1E41208410989EA86251BB> in <module>()
     89                                             accounts=accounts, preload_data=_QUARTZ_PRELOAD_DATA,
     90                                             display=True, return_quartz_data=True,
---> 91                                             threaded=quartz_createVar.get('threaded', True), need_tracking=True)
     92     _QUARTZ_CACHE['start'] = start
     93     _QUARTZ_CACHE['end'] = end

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/utils/tracking_utils.pyc in _decorator(*args, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/backtest.pyc in backtest(start, end, benchmark, universe, capital_base, initialize, handle_data, post_trading_day, commission, slippage, refresh_rate, freq, security_base, security_cost, max_history_window, accounts, threaded, display, preload_data, *args, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/backtest.pyc in bt_algorithm(clock, trading_scheduler, trading_agent, threaded)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/trading_agent.pyc in settlement(self)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/pms/pms_lite.pyc in post_trading_day(self, feedback_info, dividend, split)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz.egg/quartz/pms/pms_lite.pyc in _execute_dividend(self, account, config)

KeyError: '511230.OFCN'
```

感觉是在某天中计算 dividend 的时候出错了。但是不知道为什么，是不是需要剔除掉非交易日？