# 求助：关于MktEqudAdjGet使用报错的问题

单独试DataAPI.MktEqudAdjGet都是正常，但之前运行正常的，隔了一段时间回来现在报错，错误提示如下，是对普通用户调用参数进行限制了吗？比如不允许调用太多参数之类的？

Exception                                 Traceback (most recent call last)
<mercury-input-2-E5C0E9CD14A749168CAFFD62F77ED302> in <module>()
     90     for s in sel_stock:
     91         p = DataAPI.MktEqudAdjGet(tradeDate=next_day,secID=s, 
---> 92                                field=u"secID,secShortName,tradeDate,openPrice,closePrice,lowestPrice",isOpen="1",pandas="1")

/home/ipython/anaconda/lib/python2.7/site-packages/DataAPI/DATAYES.py in MktEqudAdjGet(secID, ticker, tradeDate, beginDate, endDate, isOpen, field, pandas)
   4335         csvString = api_base.__getCSV__(''.join(requestString), httpClient, gw=False)
   4336         if csvString is None or len(csvString) == 0 or (csvString[0] == '-' and not api_base.is_no_data_warn(csvString, False)) or csvString[0] == '{':
-> 4337             api_base.handle_error(csvString, 'MktEqudAdjGet')
   4338         elif csvString[:2] == '-1':
   4339             csvString = ''

/home/ipython/anaconda/lib/python2.7/site-packages/DataAPI/api_base.pyc in handle_error(csvString, api_name)
    191     else:
    192         result = csvString
--> 193     raise Exception(get_real_string(result))
    194 
    195 

Exception: 无效的请求参数。请检查输入参数，若仍有问题，可联系service.uqer@datayes.com